name: qpay
description: Qpay payment app


# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.8+11

environment:
  sdk: ">=2.10.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flustars: ^2.0.1
  intl: ^0.17.0
  dio: ^4.0.4
  rxdart: ^0.27.3
  common_utils: ^2.0.2
  url_launcher: ^6.0.20
  fluro: ^2.0.3
  cupertino_icons: ^1.0.4
  sprintf: ^6.0.0
  cached_network_image: ^3.1.0+1
  keyboard_actions: ^3.4.4
  oktoast: ^3.1.5
  provider: ^6.0.1
  step_progress_indicator: ^1.0.1
  device_info: ^2.0.3
  local_auth: ^2.0.1
  flutter_native_contact_picker: ^0.0.3
  another_flushbar: ^1.10.28
  dotted_border: ^2.0.0+1
  camera: ^0.9.8+1
  path_provider: ^2.0.7
  path: ^1.8.0
  group_button: ^3.3.1
  qr_code_scanner: ^1.0.0
  event_bus: ^2.0.0
  cron: ^0.5.0
  screenshot: ^1.2.3
  share_plus: ^4.0.6
  animated_splash_screen: ^1.1.0
  collection: ^1.15.0
  toggle_switch: ^1.3.0
  flutter_phone_direct_caller: ^2.1.0
  contacts_service: ^0.6.3
  permission_handler: ^9.1.0
  pinput: ^1.2.2
  otp_count_down: ^1.0.6
  connectivity: ^3.0.6
  firebase_messaging: ^11.4.2
  get_it: ^7.2.0
  flutter_local_notifications: ^9.1.4
  firebase_core: ^1.12.0
  overlay_support: ^1.2.1
  flutter_app_badger: ^1.3.0
  get: ^4.3.8
  flutter_bloc: ^8.0.1
  flutter_cupertino_datetime_picker: ^3.0.0
  image_gallery_saver: ^1.7.1
  expandable: ^5.0.1
  image_picker: ^0.8.4+4
  open_mail_app: ^0.4.4
  app_settings: ^4.1.1
  share_files_and_screenshot_widgets: ^1.0.6
  new_version: ^0.3.0
  package_info_plus: ^1.4.0
  image_cropper: ^1.5.0
  flutter_scrolling_fab_animated: ^0.1.1+1
  webview_flutter: ^3.0.1
  firebase_crashlytics: ^2.5.3
  flutter_inappwebview: 5.4.4+3
  advance_pdf_viewer: ^2.0.1

dependency_overrides:
  decimal: ^1.5.0
dev_dependencies:
  flutter_test:
    sdk: flutter
  intl: ^0.17.0
  flutter_launcher_icons:

flutter_icons:
  image_path: "assets/images/app_icon.png"
  android:  "launcher_icon"
  ios: true


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  assets:
    - assets/images/
    - assets/images/login/
    - assets/images/dashboard/
    - assets/images/cards/
  fonts:
    - family: Courier
      fonts:
        - asset: assets/fonts/cour.ttf
    - family: Inter
      fonts:
        - asset: assets/fonts/inter_bold.ttf
        - asset: assets/fonts/inter_regular.ttf
    - family: SF
      fonts:
        - asset: assets/fonts/sf_ui_regular.ttf
    - family: San
      fonts:
        - asset: assets/fonts/product_sans_bold.ttf
    - family: Helvetica
      fonts:
        - asset: assets/fonts/helvetica_neue.ttf
        - asset: assets/fonts/helvetica_neue_thin.ttf
        - asset: assets/fonts/helvetica_neue_light.ttf
        - asset: assets/fonts/helvetica_neue_medium.ttf
    - family: OCR
      fonts:
        - asset: assets/fonts/ocraext.TTF
    - family:  TakaIcon
      fonts:
        - asset: assets/fonts/TakaIcon.ttf


  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
