/// Flutter icons TakaIcon
/// Copyright (C) 2021 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  TakaIcon
///      fonts:
///       - asset: fonts/TakaIcon.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class TakaIcon {
  TakaIcon._();

  static const _kFontFam = 'TakaIcon';
  static const String _kFontPkg = null;

  static const IconData taka_icon = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
